### ISSUE TITLE
Badly aligned Badge, on the main menu with a 21:9 ration screen.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [AsianAntwan/AntsHUD#2]
https://i.imgur.com/hcOOLK8.png
Pretty self-explanatory.  Probably caused, by the fact that the hud was more adapted with a 16:9 ratio by default.

**Comment by AsianAntwan** [comment]
I knew that would happen since the Medal “xpos” was adjudged for the center of the screen instead of left or right side. That means it’ll stay the same distance from the center screen even when the screen is changing resolution. For left and right, same rule applies, but is attached to the parts where resolution is changing, so it’ll shift according. Most of the Main Menu elements are attached to the left side except the Friends Panel, so once resolution changes all of them shift and the Medal simply just stays in place.

Regardless, I was already aware of that and fixed it though I do appreciate the bug report. Should be in “Constant” branch sooner or later. 

Cheers,
Antwan
